### ISSUE TITLE
add README instructions

### ISSUE THREAD

**Issue by bondarewicz** [leafle/newman-reporter-teamcity#1]
any usage instructions would be very handy

**Comment by brettataarons** [comment]
Is this library supposed to be used as a plugin for TC or a plugin for Newman?  Any usage instructions would be fantastic.

**Comment by sergiorykov** [comment]
Agree.

Can't get it work from newman command line..

-r=cli,teamcity
-r=cli,newman-reporter-teamcity

Is it possible at al?

**Comment by sergiorykov** [comment]
Usage from code is pretty strightforward (haven't checked it out): https://github.com/postmanlabs/newman#using-newman-as-a-nodejs-module

Opened an issue for newman to clarify their position on subject with calling thirdparty reporters from CLI or just support popular CI https://github.com/postmanlabs/newman/issues/910

**Comment by brettataarons** [comment]
I tried to use it from code and couldn't get it to work.  Not much documentation on how to do that with a custom plugin from newman.   Anyway, a good solution is to just use the junit reporter and in your teamcity build click Build Features and select XML report processing and then point to the report folder you setup in the newman config (newman/ by default).

**Comment by sergiorykov** [comment]
To run from command line when newman is installed globally, reporter must be installed globally too
`npm i -g newman-reporter-teamcity`
newman team improved their documentation https://github.com/postmanlabs/newman/pull/912

**Comment by natelowry** [comment]
#5 should be good enough to get folks going.  Thanks for writing this plugin!
