### ISSUE TITLE
Support multi processes running in parallel

### ISSUE THREAD

**Issue by gqy117** [leafle/newman-reporter-teamcity#11]
First off, thank you for creating such an awesome **Newman** extension. We've been using it for quite a while.

## Senario:
When we run test cases in parallel, sometimes **TeamCity** will mismatch '**test case 1**' to '**test suite 2**'
##teamcity[testSuiteStarted name='test suite 1']
##teamcity[testSuiteStarted name='test suite 2']
##teamcity[testStarted name='test case 1' captureStandardOutput='true']
##teamcity[testFinished name='test case 1' duration='100']
##teamcity[testStarted name='test case 2' captureStandardOutput='true']
##teamcity[testFinished name='test case 2' duration='100']
##teamcity[testSuiteFinished name='test suite 2']

TeamCity would treat both '**test case 1**' and '**test case 2**' as part of '**test suite 2**'.

## Solution:
Use [flowId](https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-MessageFlowId)

I have given it a [go](https://github.com/gqy117/newman-reporter-teamcity/blob/master/lib/index.js). It works.
But I'm not happy with the fact that I required a third party library '**uuid/v4**' to get the unique id.

Any thoughts on that?

Cheers,

**Comment by leafle** [comment]
Thanks for reporting and the suggested fix. I'm sorry it took me so long to notice.

Maybe we can concatenate the process ID with a timestamp instead of requiring uuid. This isn't perfect but it seems like it'll be good enough. If you send a pull request I'll make sure to review it ASAP.
