### ISSUE TITLE
newman-reporter-teamcity generate wrong response code in the test report when test case assert failed

### ISSUE THREAD

**Issue by hujunhaorobert** [leafle/newman-reporter-teamcity#13]
I was using newman and newman-reporter-teamcity in Powershell to run the API testing.
The newman command line is : 
        newman run $DirectAGCollectionURL -e $GetEnvVarAUTest --iteration-data $DataFile -n $Iterations --folder $APIFolderNames[$i] -r cli,teamcity,json --reporter-json-export $OutputFile
Below is the just copy & past of small part of the test report generated 
...

└ Create Semaphore
##teamcity[testStarted name='Create Semaphore' captureStandardOutput='true']
  POST https://au-test.leap.services/api/v1/semaphore [201 Created, 540B, 1028ms]
  ┌
  │ 'Scenario \'No Semaphore Name\' responseCode.code=201'
  │ 'Defect API-18 is still outstanding'
  └
  √  1) Check Expected RC = 201
  √  2) Validate response against schema
  3. 3) Check SemaphoreId is NOT Created for 'No Semaphore Name' (Negative Scenario)
  √  4) Content-Type is application/json
##teamcity[testFailed name='Create Semaphore' message='3) Check SemaphoreId is NOT Created for |'No Semaphore Name|' (Negative Scenario)' details='3) Check SemaphoreId is NOT Created for |'No Semaphore Name|' (Negative Scenario) - Response code: 1028, reason: Created']
##teamcity[testFinished name='Create Semaphore' duration='1028']

Here the problem is, in the team city report, it gives wrong Response code by referring to the response time value(1028), not the real response code for the API (RC=201) . 
The expectation is  Response code: 201

My testing environment version:
In a command prompt window, type   "npm list -g --depth=0 " to get some of the details related to newman:
+-- newman@3.9.1
+-- newman-reporter-teamcity@0.1.7

**Comment by leafle** [comment]
I merged the pull request and published a new version to npm. Thanks for the fix.

**Comment by hujunhaorobert** [comment]
Thanks a lot, that is great!
