### ISSUE TITLE
warning: "teamcity" reporter could not be loaded.

### ISSUE THREAD

**Issue by eschneider999** [leafle/newman-reporter-teamcity#15]
following there instructions:
https://github.com/leafle/newman-reporter-teamcity

Tried to run my collection as per the instructions and got the following error:
warning: "teamcity" reporter could not be loaded.

teamcity was installed as per the instructions, so why can't it find it?

Note I'm using windows 10.

**Comment by eschneider999** [comment]
FYI; 

If there is a problem, you might want to indicate why?

**Comment by leafle** [comment]
That warning is coming from newman and usually indicates that the node module for the reporter is not installed in the expected location.
