### ISSUE TITLE
Reporter should be 'dominant' or don't write to log anything but teamcity commands

### ISSUE THREAD

**Issue by sergiorykov** [leafle/newman-reporter-teamcity#2]
CLI reporter is dominant. It means if there are two dominant reporters they will fight against each other and make output almost useless.

```
// Mark the CLI reporter as dominant, so that no two dominant reporters are together
PostmanCLIReporter.prototype.dominant = true;
```

I can't use `-r cli,teamcity` together - common output is awful. I need teamcity diagnostics (start/stop/success/failure) in 'real time' while everything else I can read from `cli` output in a pretty form.

**Comment by leafle** [comment]
Thanks for pointing this out, I've fixed this issue in v0.1.6.
