### ISSUE TITLE
TeamCity keep logging this exception "Incorrect property name." in logs

### ISSUE THREAD

**Issue by kharod** [leafle/newman-reporter-teamcity#4]
In my TeamCity Build logs, I see the following:

##teamcity[testStarted name='xxxxTest Namexxxx' captureStandardOutput='true']
[11:41:22]
Incorrect property name.
Valid property list format is (name( )=( )'escaped_value'( )) where escape symbol is "|"

**Comment by leafle** [comment]
This issue should be fixed after merging #8.
